//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltUretimAsamalari
    {
        public AltUretimAsamalari()
        {
            this.Uretim = new HashSet<Uretim>();
            this.UretimYetkilendirme = new HashSet<UretimYetkilendirme>();
        }
    
        public int AltUretimAsamalariId { get; set; }
        public string AltUretimAsamalariAdi { get; set; }
        public int UretimAsamalariId { get; set; }
    
        public virtual ICollection<Uretim> Uretim { get; set; }
        public virtual ICollection<UretimYetkilendirme> UretimYetkilendirme { get; set; }
    }
}
