//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsamaAyrinti
    {
        public int AsamaAyrintiId { get; set; }
        public int AsamaTarihceId { get; set; }
        public int AsamaAdlariId { get; set; }
        public Nullable<int> TeslimatMiktari { get; set; }
        public Nullable<int> TeslimEdilecekToplamMiktar { get; set; }
        public string HareketSahibi { get; set; }
        public bool Silindi { get; set; }
    
        public virtual AsamaAdlari AsamaAdlari { get; set; }
        public virtual AsamaTarihce AsamaTarihce { get; set; }
    }
}
