//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaskiMakineleri
    {
        public BaskiMakineleri()
        {
            this.BaskiEbatlari = new HashSet<BaskiEbatlari>();
            this.IsEmriBaskiMakineleri = new HashSet<IsEmriBaskiMakineleri>();
        }
    
        public int BaskiMakineleriId { get; set; }
        public string MakineAdi { get; set; }
        public bool Silindi { get; set; }
    
        public virtual ICollection<BaskiEbatlari> BaskiEbatlari { get; set; }
        public virtual ICollection<IsEmriBaskiMakineleri> IsEmriBaskiMakineleri { get; set; }
    }
}
