//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsDurumAdlari
    {
        public IsDurumAdlari()
        {
            this.IsAsamasi = new HashSet<IsAsamasi>();
        }
    
        public int IsDurumAdlari1 { get; set; }
        public string DurumAdi { get; set; }
    
        public virtual ICollection<IsAsamasi> IsAsamasi { get; set; }
    }
}
