//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsEmriOnayBilgileri
    {
        public int IsEmriID { get; set; }
        public Nullable<bool> Otokopi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Onayalindi { get; set; }
        public Nullable<bool> Reddedildi { get; set; }
        public string RedNedeni { get; set; }
        public string AdetAciklama { get; set; }
        public Nullable<bool> IsTamamlandi { get; set; }
        public Nullable<bool> OnayGeriAlindi { get; set; }
        public Nullable<bool> KismiTamam { get; set; }
        public Nullable<bool> YarimKaldi { get; set; }
        public int IsEmriBaskiBilgileriId { get; set; }
        public Nullable<bool> Silindi { get; set; }
    
        public virtual IsEmri IsEmri { get; set; }
        public virtual IsEmri IsEmri1 { get; set; }
        public virtual IsEmri IsEmri2 { get; set; }
    }
}
