//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsEmriYokIsParcasi
    {
        public int Id { get; set; }
        public int IsEmriId { get; set; }
        public int YokIsParcasiId { get; set; }
    
        public virtual YokIsParcasi YokIsParcasi { get; set; }
        public virtual IsEmri IsEmri { get; set; }
    }
}
