//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsEmriTeknikBilgiler
    {
        public int IsEmriId { get; set; }
        public Nullable<int> KesimBoyutlariId { get; set; }
        public Nullable<int> Adedi { get; set; }
        public Nullable<int> Cilt { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public string IcBaskiRenk { get; set; }
        public string KapakBaskiRenk { get; set; }
        public int IsEmriTeknikBilgilerId { get; set; }
        public Nullable<int> IsCinsiId { get; set; }
        public Nullable<bool> Silindi { get; set; }
        public int BitmisIsBoyutlariId { get; set; }
    
        public virtual BitmisIsBoyutlari BitmisIsBoyutlari { get; set; }
        public virtual CiltTipleri CiltTipleri { get; set; }
        public virtual IsCinsi IsCinsi { get; set; }
        public virtual IsEmri IsEmri { get; set; }
        public virtual BaskiEbatlari BaskiEbatlari { get; set; }
    }
}
