//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KritikSeviye
    {
        public int KritikSeviyeId { get; set; }
        public Nullable<int> KritikStok { get; set; }
        public Nullable<int> GuncelStok { get; set; }
        public Nullable<int> AltGruplarId { get; set; }
    
        public virtual AltGruplar AltGruplar { get; set; }
    }
}
