//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maliyet
    {
        public long MaliyetId { get; set; }
        public Nullable<int> IsEmriId { get; set; }
        public Nullable<decimal> IdariGiderlerBirimFiyat { get; set; }
        public Nullable<double> IdariGiderlerMiktar { get; set; }
        public Nullable<decimal> TasarimMizanDizgiIscilikBirimFiyat { get; set; }
        public Nullable<double> TasarimMizanDizgiIscilikMiktar { get; set; }
        public Nullable<decimal> CiktiRenkliBirimFiyat { get; set; }
        public Nullable<double> CiktiRenkliMiktar { get; set; }
        public Nullable<decimal> SBCiktiBFiyat { get; set; }
        public Nullable<double> SBCiktiMiktar { get; set; }
        public Nullable<decimal> FilmBirimFiyat { get; set; }
        public Nullable<double> FilmMiktar { get; set; }
        public Nullable<decimal> CTPBirimFiyat { get; set; }
        public Nullable<double> CTPMiktar { get; set; }
        public Nullable<decimal> OzosolKalipBirimFiyat { get; set; }
        public Nullable<double> OzosolMiktar { get; set; }
        public Nullable<decimal> MasterKalipBirimFiyat { get; set; }
        public Nullable<double> MasterKalipMiktar { get; set; }
        public Nullable<decimal> ElektrostatikBirimFiyat { get; set; }
        public Nullable<double> ElektrostatikMiktar { get; set; }
        public Nullable<decimal> IcKagitBirimFiyat { get; set; }
        public Nullable<double> IcKagitMiktar { get; set; }
        public Nullable<decimal> KapakKagitBirimFiyat { get; set; }
        public Nullable<double> KapakKagitMiktar { get; set; }
        public Nullable<decimal> DigerKagitBirimFiyat { get; set; }
        public Nullable<double> DigerKagitMiktar { get; set; }
        public Nullable<decimal> RyobiOfsetBirimFiyat { get; set; }
        public Nullable<double> RyobiOfseMiktar { get; set; }
        public Nullable<decimal> GestetnerOfsetBirimFiyat { get; set; }
        public Nullable<double> GestetnerOfsetMiktar { get; set; }
        public Nullable<decimal> RizoMZ770DijitalBirimFiyat { get; set; }
        public Nullable<double> RizoMZ770DijitaMiktar { get; set; }
        public Nullable<decimal> Gestetner6244DijitalBirimFiyat { get; set; }
        public Nullable<double> Gestetner6244DijitaMiktar { get; set; }
        public Nullable<decimal> HamKagitKesimiBirimFiyat { get; set; }
        public Nullable<double> HamKagitKesimMiktar { get; set; }
        public Nullable<decimal> HarmanBirimFiyat { get; set; }
        public Nullable<double> HarmanMiktar { get; set; }
        public Nullable<decimal> KapakTakmaBirimFiyat { get; set; }
        public Nullable<double> KapakTakmaMiktar { get; set; }
        public Nullable<decimal> KirimBirimFiyat { get; set; }
        public Nullable<double> KirimMiktar { get; set; }
        public Nullable<decimal> DikisBirimFiyat { get; set; }
        public Nullable<double> DikisMiktar { get; set; }
        public Nullable<decimal> SonKesimBirimFiyat { get; set; }
        public Nullable<double> SonKesimMiktar { get; set; }
        public Nullable<decimal> PaketlemeBirimFiyat { get; set; }
        public Nullable<double> PaketlemeMiktar { get; set; }
        public Nullable<decimal> IscilikBirimFiyat { get; set; }
        public Nullable<double> IscilikMiktar { get; set; }
        public Nullable<decimal> DisGiderlerBirimFiyat { get; set; }
        public Nullable<double> DisGiderlerMiktar { get; set; }
    
        public virtual IsEmri IsEmri { get; set; }
        public virtual IsEmri IsEmri1 { get; set; }
    }
}
