//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeslimatRaporu
    {
        public int TeslimatRaporuId { get; set; }
        public Nullable<int> IsEmriId { get; set; }
        public System.Guid TeslimEdenPersonel { get; set; }
        public string TeslimAlan { get; set; }
        public int TeslimatMiktari { get; set; }
        public System.DateTime Tarih { get; set; }
    
        public virtual IsEmri IsEmri { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
