//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimNotlari
    {
        public int UretimNotlariId { get; set; }
        public string TasarimaOnayVeren { get; set; }
        public string BaskiOncesiHazirlikNotu { get; set; }
        public string BaskiNotu { get; set; }
        public string MucellithaneNotu { get; set; }
        public string IsKesimiProgramNo { get; set; }
        public string PaketBilgileri { get; set; }
        public int IsEmriId { get; set; }
    
        public virtual IsEmri IsEmri { get; set; }
    }
}
