//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimYetkilendirme
    {
        public int UretimYetkilendirmeId { get; set; }
        public System.Guid PersonelUN { get; set; }
        public int AltUretimAsamalariId { get; set; }
        public int IsEmriId { get; set; }
        public string Aciklama { get; set; }
    
        public virtual AltUretimAsamalari AltUretimAsamalari { get; set; }
        public virtual IsEmri IsEmri { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
