//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vKagitTuketimi
    {
        public string KulanilanIcKagitCinsi { get; set; }
        public Nullable<int> IcKagitNet { get; set; }
        public Nullable<int> IcKagitFire { get; set; }
        public string IcBaskiBoyutu { get; set; }
        public string IcTabakaKesimi { get; set; }
        public string KulanilanKapakKagitCinsi { get; set; }
        public string KapakBaskiBoyutu { get; set; }
        public Nullable<int> kapaknet { get; set; }
        public string KapakTabakaKesimi { get; set; }
        public Nullable<int> kapakfire { get; set; }
        public int IsEmriId { get; set; }
        public string Isno { get; set; }
        public string tarihsayi { get; set; }
        public string adi { get; set; }
        public Nullable<System.DateTime> KabulTarihi { get; set; }
        public Nullable<System.DateTime> teslimtarihi { get; set; }
        public string Aciklama { get; set; }
        public string BirimAdi { get; set; }
    }
}
