//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AktiviteSahipleri
    {
        public int AktiviteSahipleriId { get; set; }
        public int IsEmriId { get; set; }
        public string AktiviteSahibi { get; set; }
        public int AktiviteAdlariId { get; set; }
    
        public virtual AktiviteAdlari AktiviteAdlari { get; set; }
    }
}
