//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsamaAdlari
    {
        public AsamaAdlari()
        {
            this.AsamaAyrinti = new HashSet<AsamaAyrinti>();
        }
    
        public int AsamaAdlariId { get; set; }
        public string AsamaAdi { get; set; }
    
        public virtual ICollection<AsamaAyrinti> AsamaAyrinti { get; set; }
    }
}
