//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaskiEbatlari
    {
        public BaskiEbatlari()
        {
            this.IsEmriBaskiMakineleri = new HashSet<IsEmriBaskiMakineleri>();
            this.IsEmriBaskiMakineleri1 = new HashSet<IsEmriBaskiMakineleri>();
            this.IsEmriKullanilacakKagit = new HashSet<IsEmriKullanilacakKagit>();
            this.IsEmriKullanilacakKagit1 = new HashSet<IsEmriKullanilacakKagit>();
            this.IsEmriTeknikBilgiler = new HashSet<IsEmriTeknikBilgiler>();
        }
    
        public int BaskiEbatlariId { get; set; }
        public string Boyut { get; set; }
        public int BaskiMakineleriId { get; set; }
        public decimal BirimFiyat { get; set; }
        public bool Silindi { get; set; }
    
        public virtual BaskiMakineleri BaskiMakineleri { get; set; }
        public virtual ICollection<IsEmriBaskiMakineleri> IsEmriBaskiMakineleri { get; set; }
        public virtual ICollection<IsEmriBaskiMakineleri> IsEmriBaskiMakineleri1 { get; set; }
        public virtual ICollection<IsEmriKullanilacakKagit> IsEmriKullanilacakKagit { get; set; }
        public virtual ICollection<IsEmriKullanilacakKagit> IsEmriKullanilacakKagit1 { get; set; }
        public virtual ICollection<IsEmriTeknikBilgiler> IsEmriTeknikBilgiler { get; set; }
    }
}
