//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FizikselBirim
    {
        public FizikselBirim()
        {
            this.AltGruplar = new HashSet<AltGruplar>();
            this.StokGiris = new HashSet<StokGiris>();
        }
    
        public int FizikselBirimId { get; set; }
        public string Nicelik { get; set; }
        public string FizikselBirim1 { get; set; }
    
        public virtual ICollection<AltGruplar> AltGruplar { get; set; }
        public virtual ICollection<StokGiris> StokGiris { get; set; }
    }
}
