//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKBSBirim
    {
        public IKBSBirim()
        {
            this.IsEmri = new HashSet<IsEmri>();
        }
    
        public System.Guid BirimUN { get; set; }
        public Nullable<System.Guid> UstBirimUN { get; set; }
        public Nullable<int> BirimGrupId { get; set; }
        public string Adi { get; set; }
        public Nullable<System.Guid> BirimAmirUN { get; set; }
        public Nullable<System.Guid> MuhasebeKodUN { get; set; }
        public string Kodu { get; set; }
        public string IdariKimlikKodu { get; set; }
        public Nullable<int> IlId { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Faks { get; set; }
        public string Eposta { get; set; }
        public Nullable<bool> PersonelYemekUcretiAlacakMi { get; set; }
        public string SSKID { get; set; }
        public string SskKullaniciAd { get; set; }
        public Nullable<System.DateTime> KurulusTar { get; set; }
        public decimal SskIsverenOran { get; set; }
        public double SskIsciOran { get; set; }
        public decimal SskIsverenIssizlikOran { get; set; }
        public decimal SskIsciIssizlikOran { get; set; }
        public string KontrolNo { get; set; }
        public string VergiNo { get; set; }
        public bool Silindi { get; set; }
        public string HiyerarsiKod { get; set; }
        public string LatLong { get; set; }
        public Nullable<decimal> GssIsverenOran { get; set; }
        public Nullable<decimal> GssIsciOran { get; set; }
        public Nullable<System.DateTime> KapanisTar { get; set; }
    
        public virtual ICollection<IsEmri> IsEmri { get; set; }
    }
}
