//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsAsamasi
    {
        public string Isno { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public int IsAsamasiId { get; set; }
        public Nullable<int> TeslimEdilen { get; set; }
        public Nullable<int> ToplamMiktar { get; set; }
        public Nullable<int> IsEmriId { get; set; }
        public string IsAdi { get; set; }
        public Nullable<System.DateTime> KabulTarihi { get; set; }
        public string IlgiliBirim { get; set; }
        public Nullable<int> IsDurumAdlariId { get; set; }
    
        public virtual IsDurumAdlari IsDurumAdlari { get; set; }
    }
}
