//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsEmri
    {
        public IsEmri()
        {
            this.IsEmriOnayBilgileri = new HashSet<IsEmriOnayBilgileri>();
            this.IsEmriOnayBilgileri1 = new HashSet<IsEmriOnayBilgileri>();
            this.IsEmriBaskiMakineleri = new HashSet<IsEmriBaskiMakineleri>();
            this.IsEmriFilmGiderleri = new HashSet<IsEmriFilmGiderleri>();
            this.IsEmriKalipMalzemeGiderleri = new HashSet<IsEmriKalipMalzemeGiderleri>();
            this.IsEmriKullanilacakKagit = new HashSet<IsEmriKullanilacakKagit>();
            this.IsEmriKullanilanLaminasyonlar = new HashSet<IsEmriKullanilanLaminasyonlar>();
            this.IsEmriOnayBilgileri2 = new HashSet<IsEmriOnayBilgileri>();
            this.IsEmriOtokopi = new HashSet<IsEmriOtokopi>();
            this.IsEmriUploadDosyalari = new HashSet<IsEmriUploadDosyalari>();
            this.IsEmriYokIsParcasi = new HashSet<IsEmriYokIsParcasi>();
            this.KullanilanKagitlar = new HashSet<KullanilanKagitlar>();
            this.Maliyet = new HashSet<Maliyet>();
            this.Maliyet1 = new HashSet<Maliyet>();
            this.MucellithaneProgramNoPaketBilgileri = new HashSet<MucellithaneProgramNoPaketBilgileri>();
            this.StokHareketSilmeTarihce = new HashSet<StokHareketSilmeTarihce>();
            this.TeslimatRaporu = new HashSet<TeslimatRaporu>();
            this.Uretim = new HashSet<Uretim>();
            this.UretimNotlari = new HashSet<UretimNotlari>();
            this.UretimYetkilendirme = new HashSet<UretimYetkilendirme>();
            this.IsEmriTeknikBilgiler = new HashSet<IsEmriTeknikBilgiler>();
        }
    
        public int IsEmriId { get; set; }
        public string IsNo { get; set; }
        public string TarihSayi { get; set; }
        public string Adi { get; set; }
        public string Personel { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> KabulTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public string Aciklama { get; set; }
        public int BirimId { get; set; }
        public Nullable<bool> Silindi { get; set; }
        public string IlgiliEPosta { get; set; }
        public Nullable<System.Guid> IKBSBirimUN { get; set; }
    
        public virtual Birim Birim { get; set; }
        public virtual IKBSBirim IKBSBirim { get; set; }
        public virtual ICollection<IsEmriOnayBilgileri> IsEmriOnayBilgileri { get; set; }
        public virtual ICollection<IsEmriOnayBilgileri> IsEmriOnayBilgileri1 { get; set; }
        public virtual ICollection<IsEmriBaskiMakineleri> IsEmriBaskiMakineleri { get; set; }
        public virtual ICollection<IsEmriFilmGiderleri> IsEmriFilmGiderleri { get; set; }
        public virtual ICollection<IsEmriKalipMalzemeGiderleri> IsEmriKalipMalzemeGiderleri { get; set; }
        public virtual ICollection<IsEmriKullanilacakKagit> IsEmriKullanilacakKagit { get; set; }
        public virtual ICollection<IsEmriKullanilanLaminasyonlar> IsEmriKullanilanLaminasyonlar { get; set; }
        public virtual ICollection<IsEmriOnayBilgileri> IsEmriOnayBilgileri2 { get; set; }
        public virtual ICollection<IsEmriOtokopi> IsEmriOtokopi { get; set; }
        public virtual ICollection<IsEmriUploadDosyalari> IsEmriUploadDosyalari { get; set; }
        public virtual ICollection<IsEmriYokIsParcasi> IsEmriYokIsParcasi { get; set; }
        public virtual ICollection<KullanilanKagitlar> KullanilanKagitlar { get; set; }
        public virtual ICollection<Maliyet> Maliyet { get; set; }
        public virtual ICollection<Maliyet> Maliyet1 { get; set; }
        public virtual ICollection<MucellithaneProgramNoPaketBilgileri> MucellithaneProgramNoPaketBilgileri { get; set; }
        public virtual ICollection<StokHareketSilmeTarihce> StokHareketSilmeTarihce { get; set; }
        public virtual ICollection<TeslimatRaporu> TeslimatRaporu { get; set; }
        public virtual ICollection<Uretim> Uretim { get; set; }
        public virtual ICollection<UretimNotlari> UretimNotlari { get; set; }
        public virtual ICollection<UretimYetkilendirme> UretimYetkilendirme { get; set; }
        public virtual ICollection<IsEmriTeknikBilgiler> IsEmriTeknikBilgiler { get; set; }
    }
}
