//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsEmriKalipMalzemeGiderleri
    {
        public int IsEmriId { get; set; }
        public int IsEmriKalipMalzemeGiderleriId { get; set; }
        public Nullable<bool> Ic { get; set; }
        public Nullable<bool> Dis { get; set; }
        public int AltGruplarId { get; set; }
        public int KullanilanKalipSayisi { get; set; }
        public Nullable<bool> Silindi { get; set; }
    
        public virtual IsEmri IsEmri { get; set; }
        public virtual AltGruplar AltGruplar { get; set; }
    }
}
