//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsEmriEski
    {
        public int ObjectID { get; set; }
        public string isno { get; set; }
        public string tarihsayi { get; set; }
        public string adi { get; set; }
        public string birim { get; set; }
        public string personel { get; set; }
        public string telefon { get; set; }
        public Nullable<System.DateTime> kabultarihi { get; set; }
        public Nullable<System.DateTime> teslimtarihi { get; set; }
        public string aciklama1 { get; set; }
        public string cinsi { get; set; }
        public string ebadi { get; set; }
        public Nullable<int> adedi { get; set; }
        public string cilt { get; set; }
        public string sayfasayisi { get; set; }
        public string icbaskirenk { get; set; }
        public string kapakbaskirenk { get; set; }
        public Nullable<bool> selefon { get; set; }
        public Nullable<bool> lak { get; set; }
        public Nullable<bool> vernik { get; set; }
        public string icfilm { get; set; }
        public string kapakfilm { get; set; }
        public Nullable<bool> ozosolic { get; set; }
        public Nullable<bool> estaticic { get; set; }
        public Nullable<bool> masteric { get; set; }
        public Nullable<bool> CTPic { get; set; }
        public Nullable<bool> ozosolkap { get; set; }
        public Nullable<bool> estatickap { get; set; }
        public bool masterkap { get; set; }
        public Nullable<bool> CTPkap { get; set; }
        public Nullable<decimal> ozic { get; set; }
        public Nullable<decimal> esic { get; set; }
        public Nullable<decimal> mtic { get; set; }
        public Nullable<decimal> CTic { get; set; }
        public Nullable<decimal> ozkap { get; set; }
        public Nullable<decimal> eskap { get; set; }
        public Nullable<decimal> mtkap { get; set; }
        public Nullable<decimal> CTkap { get; set; }
        public string ickagitcins { get; set; }
        public string ickagitgram { get; set; }
        public string icebad { get; set; }
        public Nullable<bool> rexrotaryic { get; set; }
        public Nullable<bool> gestetneric { get; set; }
        public Nullable<bool> abdickic { get; set; }
        public Nullable<bool> multilitic { get; set; }
        public Nullable<bool> ryobiic { get; set; }
        public Nullable<bool> canonic { get; set; }
        public Nullable<bool> rizoic { get; set; }
        public Nullable<bool> rexrotarykap { get; set; }
        public Nullable<bool> gestetnerkap { get; set; }
        public Nullable<bool> abdickkap { get; set; }
        public Nullable<bool> multilitkap { get; set; }
        public Nullable<bool> ryobikap { get; set; }
        public Nullable<bool> canonkap { get; set; }
        public Nullable<bool> rizokap { get; set; }
        public Nullable<decimal> icknet { get; set; }
        public Nullable<decimal> ickfire { get; set; }
        public string ickbaski { get; set; }
        public string icktabaka { get; set; }
        public string kapakcins { get; set; }
        public string kapakgram { get; set; }
        public string kapakebad { get; set; }
        public Nullable<decimal> kapaknet { get; set; }
        public Nullable<decimal> kapakfire { get; set; }
        public string kapakbaski { get; set; }
        public string kapaktabaka { get; set; }
        public string icbaskiebadi { get; set; }
        public string kapakbaskiebadi { get; set; }
        public Nullable<decimal> icbaskimiktari { get; set; }
        public Nullable<decimal> kapakbaskimiktari { get; set; }
        public Nullable<bool> otokopi { get; set; }
        public string aciklama2 { get; set; }
        public Nullable<bool> onaybekleyen { get; set; }
        public Nullable<bool> onayalinan { get; set; }
        public Nullable<bool> isitamamlanan { get; set; }
        public Nullable<bool> reddedilen { get; set; }
        public string rednedeni { get; set; }
        public string adetaciklama { get; set; }
        public Nullable<bool> IsTamamlandi { get; set; }
        public Nullable<bool> OnayGeriAlindi { get; set; }
        public Nullable<bool> KismiTamam { get; set; }
        public Nullable<bool> YarimKaldi { get; set; }
    }
}
