//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsEmriBaskiMakineleri
    {
        public int IsEmriBaskiMakineleriId { get; set; }
        public int IsEmriId { get; set; }
        public int BaskiMakineleriId { get; set; }
        public int IcBaskiMiktari { get; set; }
        public int KapakBaskiMiktari { get; set; }
        public int IcBaskiEbadi { get; set; }
        public int KapakBaskiEbadi { get; set; }
        public string MakineninKullanildigiYer { get; set; }
    
        public virtual IsEmri IsEmri { get; set; }
        public virtual BaskiEbatlari BaskiEbatlari { get; set; }
        public virtual BaskiEbatlari BaskiEbatlari1 { get; set; }
        public virtual BaskiMakineleri BaskiMakineleri { get; set; }
    }
}
