//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public Personel()
        {
            this.Roller = new HashSet<Roller>();
            this.TeslimatRaporu = new HashSet<TeslimatRaporu>();
            this.Uretim = new HashSet<Uretim>();
            this.UretimYetkilendirme = new HashSet<UretimYetkilendirme>();
            this.StokGiris = new HashSet<StokGiris>();
        }
    
        public System.Guid PersonelUN { get; set; }
        public string PersonelAdiSoyadi { get; set; }
        public int SicilNo { get; set; }
        public bool Admin { get; set; }
        public string EPosta { get; set; }
        public bool Silindi { get; set; }
    
        public virtual ICollection<Roller> Roller { get; set; }
        public virtual ICollection<TeslimatRaporu> TeslimatRaporu { get; set; }
        public virtual ICollection<Uretim> Uretim { get; set; }
        public virtual ICollection<UretimYetkilendirme> UretimYetkilendirme { get; set; }
        public virtual ICollection<StokGiris> StokGiris { get; set; }
    }
}
