//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;

    public partial class StokGiris
    {
        public int StokGirisId { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public System.DateTime Tarih { get; set; }
        public int AltGruplarId { get; set; }
        public int FizikselBirimId { get; set; }
        public string AlindigiFirmaAdi { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public System.DateTime FaturaTarihi { get; set; }
        public string FaturaNo { get; set; }
        [DisplayFormat(DataFormatString = "{0:F3}", ApplyFormatInEditMode = true)]
        public decimal BirimFiyat { get; set; }
        public decimal Miktar { get; set; }
        public System.Guid StokGirisiniYapan { get; set; }

        public virtual AltGruplar AltGruplar { get; set; }
        public virtual FizikselBirim FizikselBirim { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
