//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokGruplari
    {
        public StokGruplari()
        {
            this.StokGruplariSilmeTarihce = new HashSet<StokGruplariSilmeTarihce>();
            this.AltGruplar = new HashSet<AltGruplar>();
        }
    
        public int StokGruplariId { get; set; }
        public string StokGrupAdi { get; set; }
        public Nullable<bool> Silindi { get; set; }
    
        public virtual ICollection<StokGruplariSilmeTarihce> StokGruplariSilmeTarihce { get; set; }
        public virtual ICollection<AltGruplar> AltGruplar { get; set; }
    }
}
