//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMatbaa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YokIsParcasi
    {
        public YokIsParcasi()
        {
            this.IsEmriYokIsParcasi = new HashSet<IsEmriYokIsParcasi>();
        }
    
        public int Id { get; set; }
        public string YokIsParcasiAdi { get; set; }
    
        public virtual ICollection<IsEmriYokIsParcasi> IsEmriYokIsParcasi { get; set; }
    }
}
